#################################################
# Lamp sensors
#################################################

- platform: template
  sensors:
    lamp_status_spalnia_stol:
      friendly_name: "Статус лампы в спальне на столе"
      value_template: >
        {% if is_state('light.spalnia_stol', "on") %}On
        {% elif is_state('light.spalnia_stol', "off") %}Off
        {% else %}unavailable
        {% endif %}
    lamp_status_detskaia:
      friendly_name: "Статус лампы в детской"
      value_template: >
        {% if is_state('light.detskaia', "on") %}On
        {% elif is_state('light.detskaia', "off") %}Off
        {% else %}unavailable
        {% endif %}
    lamp_status_kukhnia_lenta:
      friendly_name: "Статус подсветки кухни"
      value_template: >
        {% if is_state('light.kukhnia_lenta', "on") %}On
        {% elif is_state('light.kukhnia_lenta', "off") %}Off
        {% else %}unavailable
        {% endif %}
    lamp_status_kukhnia_liustra:
      friendly_name: "Статус люстры на кухне"
      value_template: >
        {% if is_state('light.kukhnia_liustra', "on") %}On
        {% elif is_state('light.kukhnia_liustra', "off") %}Off
        {% else %}unavailable
        {% endif %}