title: 'Home, Sweeet Home...'
views:
  - !include lovelace/views/vi_home.yaml
  - !include lovelace/views/vi_shopping_list.yaml
  - !include lovelace/views/vi_climate.yaml
  - !include lovelace/views/vi_light.yaml
  - !include lovelace/views/vi_vacuum.yaml
  - !include lovelace/views/vi_media.yaml
  - !include lovelace/views/vi_security.yaml
  - !include lovelace/views/vi_water.yaml
  - !include lovelace/views/vi_electricity.yaml
  - !include lovelace/views/vi_stats.yaml
  - !include lovelace/views/vi_plants.yaml
  - !include lovelace/views/vi_new_year.yaml