#################################################
# Cameras, cctv, etc...
#################################################

- platform: mjpeg
  name: CloudCam01
  mjpeg_url: 'http://a0d7b954-motioneye:8081'
  username: !secret motioneye_user
  password: !secret motioneye_pass
  authentication: digest
- platform: generic
  name: DafangCam-01-RTSP
  stream_source: !secret dafangcam_01_rtsp_stream_url
  still_image_url: !secret dafangcam_01_snapshot_url
  verify_ssl: false
- platform: mjpeg
  name: DafangCam-01-MJPEG
  mjpeg_url: !secret dafangcam_01_mjpeg_image_url
  username: !secret dafangcam_01_username
  password: !secret dafangcam_01_password
  verify_ssl: false
- platform: generic
  name: DafangCam-02-RTSP
  stream_source: !secret dafangcam_02_rtsp_stream_url
  still_image_url: !secret dafangcam_02_snapshot_url
  verify_ssl: false
- platform: mjpeg
  name: DafangCam-02-MJPEG
  mjpeg_url: !secret dafangcam_02_mjpeg_image_url
  username: !secret dafangcam_02_username
  password: !secret dafangcam_02_password
  verify_ssl: false
#- platform: generic
#  name: Baurer Camera
#  still_image_url: 'http://172.16.16.217/cgi/jpg/image.cgi'
#  stream_source: !secret baurercamera_stream_url
#  verify_ssl: false
#  framerate: 30
#- platform: ffmpeg
#  name: Baurer Camera
#  input: !secret baurercamera_stream_url
#  extra_arguments: -an