#################################################
# Switches
#################################################

- platform: wake_on_lan
  name: SamsungTV-UE43RU7470-WOL
  host: SamsungTV-43RU7470-Eth.home.intra
  mac: 8c:79:f5:51:2f:d1
  turn_off:
    service: switch.turn_on
    entity_id: switch.smartir_02_tv_samsung_power

# - platform: template
#   switches:

#     samsungtv_40c5100:
#       value_template: "{{ is_state('binary_sensor.samsungtv_40c5100', 'on') }}"
#       availability_template: "{{ is_state('binary_sensor.smartir_01_status', 'on') }}"
#       turn_on:
#         action: switch.turn_on
#         target:
#           entity_id: switch.smartir_01_tv_samsung_power
#       turn_off:
#         action: script.turn_on
#         target:
#           entity_id: script.power_off_samsungtv_40c5100
#       icon_template: >-
#         {% if is_state('binary_sensor.samsungtv_40c5100', 'on') %}
#           mdi:television
#         {% else %}
#           mdi:television-off
#         {% endif %}

#     samsungtv_46es5507:
#       value_template: "{{ is_state('media_player.ue46es5507', 'on') }}"
#       turn_on:
#         action: shell_command.chromecast_tv_on
#         data:
#           ip_addr: "172.16.16.211"
#       turn_off:
#         action: media_player.turn_off
#         data:
#           entity_id: media_player.ue46es5507
#       icon_template: >-
#         {% if is_state('media_player.ue46es5507', 'on') %}
#           mdi:television
#         {% else %}
#           mdi:television-off
#         {% endif %}
