esphome:
  name: ${board_name}

esp32:
  board: ${esp_board}
  framework:
    type: arduino

improv_serial:

logger:

captive_portal:

api:
  encryption:
    key: !secret esphome_api_key
  reboot_timeout: 5min

ota:
  - platform: esphome
    password: !secret esphome_ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: ${board_name} RSSI
    update_interval: 60s
    internal: false

binary_sensor:
  - platform: status
    name: ${board_name} Status
    internal: false

button:
  - platform: restart
    name: ${board_name} Restart

  - platform: safe_mode
    name: ${board_name} Restart (Safe Mode)
