#################################################
# Notifications
#################################################

- alias: "Home Presence Alert"
  id: 12b0184c-bb8b-436a-887a-733d0ddac126
  mode: parallel
  triggers:
    trigger: state
    entity_id: person.alexander, person.irina, person.galina, person.tatiana, person.olga, person.egor
  conditions:
    - and:
      #      - condition: template
      #        value_template: "{{ states('sensor.uptime') != '0.0' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  actions:
    - action: notify.telegram_group_flat_1
      data:
        message: >
          {{ trigger.to_state.attributes.friendly_name }}
          {% if trigger.to_state.state == 'home' %}дома!
          {% elif trigger.to_state.state == 'Дача' %}на даче!
          {% else %}скорее всего вне дома.
          {% endif %}

- alias: Entrance Door - Opened
  id: 067c832a-9626-4f61-8d19-444d6156e889
  triggers:
    trigger: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: "off"
    to: "on"
  actions:
    action: notify.telegram_group_flat_1
    data:
      message: Открыта входная дверь!

- alias: Entrance Door - Closed
  id: c6df423a-a1ec-41fb-b600-3874ffef758b
  triggers:
    trigger: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: "on"
    to: "off"
  actions:
    action: notify.telegram_group_flat_1
    data:
      message: Входная дверь закрыта.

- alias: "Torrent Completed [notify to group system]"
  id: fe45c917-f489-4c38-a3a1-c66e5fedb07f
  triggers:
    trigger: event
    event_type: transmission_downloaded_torrent
  actions:
    action: notify.telegram_group_system
    data:
      message: "Загрузка torrent-файла завершена"

- alias: "Полнолуние [notify to group system]"
  id: d698bdcc-4ce9-4954-a118-8a1f29cf327e
  triggers:
    trigger: state
    entity_id: sensor.moon
    to: "full_moon"
  actions:
    action: notify.telegram_group_system
    data:
      message: "Сегодня полнолуние!"

- alias: Gas Alert
  id: 0ca74008-65a2-4ed1-b860-e27e57b216f2
  triggers:
    trigger: state
    entity_id: binary_sensor.0x00158d000413b210_gas
    from: "off"
    to: "on"
  actions:
    - action: telegram_bot.send_message
      data:
        target: !secret tlg_group_flat_1
        title: "*Внимание!*"
        message: |
          Сработал датчик *газа* на кухне.
          Откройте окна и перекройте подачу газа (за холодильником).
        inline_keyboard:
          - "Отключить датчик:/poweroff_gas_sensor"

- alias: Gas Alert - Telegram control - poweroff_gas_sensor
  id: 3254a184-a04f-4b31-bbe9-1a00e403f134
  triggers:
    trigger: event
    event_type: telegram_callback
    event_data:
      data: "/poweroff_gas_sensor"
  actions:
    - action: switch.turn_off
      target:
        entity_id: switch.blitzwolf_shp13_02_3ad702fe_on_off
    - action: telegram_bot.answer_callback_query
      data:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Команда отправлена"
    - action: telegram_bot.edit_message
      data:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: "*Внимание!*"
        message: |
          Сработал датчик *газа* на кухне.
          Датчик *газа* отключен!

- alias: Gas Alert - Sensor Powered Off More Than 30 Min
  id: 3e69fa5f-34f2-4e5e-86e2-467aad2420b6
  triggers:
    trigger: state
    entity_id: switch.blitzwolf_shp13_02_3ad702fe_on_off
    to: "off"
    for: "00:30:00"
  actions:
    - action: telegram_bot.send_message
      data:
        target: !secret tlg_group_flat_1
        title: "*Внимание!*"
        message: |
          Питание датчика *газа* отключено более 30 минут!
        inline_keyboard:
          - "Включить датчик:/poweron_gas_sensor"

- alias: Gas Alert - Telegram control - poweroff_gas_sensor
  id: 50892fe7-741c-4b4d-a71c-a498be52d6b7
  triggers:
    trigger: event
    event_type: telegram_callback
    event_data:
      data: "/poweron_gas_sensor"
  actions:
    - action: switch.turn_on
      target:
        entity_id: switch.blitzwolf_shp13_02_3ad702fe_on_off
    - action: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Команда отправлена"
    - action: telegram_bot.edit_message
      data:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        title: "*Внимание!*"
        message: |
          Питание датчика *газа* отключено более 30 минут!
          Датчик *газа* включен!

- alias: Boiler - Low Temperature Alert
  id: fe98880b-2fcd-4b6f-9ded-adc174b9b958
  triggers:
    - trigger: numeric_state
      entity_id: sensor.boiler_water_temp
      below: 50
    - trigger: numeric_state
      entity_id: sensor.boiler_water_temp
      below: 40
    - trigger: numeric_state
      entity_id: sensor.boiler_water_temp
      below: 30
  conditions:
    condition: template
    value_template: "{{ (trigger.to_state.state | int) != 0 }}"
  actions:
    - action: notify.telegram_group_flat_1
      data:
        title: "*Внимание!*"
        message: |
          Температура воды в бойлере *{{ trigger.to_state.state }}*°C

- alias: Huawei E5372 - New Unread SMS Alert
  id: a3215213-fe61-43f1-8eb4-ea572a4acee2
  triggers:
    - trigger: state
      entity_id: sensor.huawei_e5372_sms_unread
  conditions:
    - condition: template
      value_template: >
        {% set ignore = ['unknown', 'unavailable', 'none', None, null, '', 'null'] %}
        {{ trigger.to_state.state not in ignore and trigger.from_state.state != '' }}
    - condition: template
      value_template: >
        {{ (trigger.to_state.state | int) > (trigger.from_state.state | int) }}
  actions:
    - action: notify.telegram_group_system
      data:
        message: |
          _Huawei E5372_, Непрочитанных SMS: *{{ states('sensor.huawei_e5372_sms_unread') }}*, новых: *{{ (trigger.to_state.state | int ) - (trigger.from_state.state | int) }}*

- alias: Kettle - Boil Finished Notification
  id: c5eaa742-7ea5-4c0b-8d43-d3ce69232a3e
  triggers:
    - trigger: state
      entity_id: binary_sensor.kettle_status
      from: "on"
      to: "off"
  conditions: "{{ states('input_boolean.ha_shutdown') == 'off' }}"
  actions:
    - action: notify.telegram_group_flat_1
      data:
        message: Чайник *вскипел*!

- alias: Washing Machine - Wash Finished Notification
  id: eed153ad-dca8-464d-8cc5-b30421eec1a1
  triggers:
    - trigger: state
      entity_id: binary_sensor.washer_status
      from: "on"
      to: "off"
  conditions: "{{ states('input_boolean.ha_shutdown') == 'off' }}"
  actions:
    - action: notify.telegram_group_flat_1
      data:
        title: "Стиральная машина:"
        message: Стирка *закончена*, не забудьте достать белье.

- alias: Dryer Machine - Drying Finished Notification
  id: e572fd6c-06d2-4c34-a218-4b709734c6e0
  triggers:
    - trigger: state
      entity_id: binary_sensor.dryer_status
      from: "on"
      to: "off"
  conditions: "{{ states('input_boolean.ha_shutdown') == 'off' }}"
  actions:
    - action: notify.telegram_group_flat_1
      data:
        title: "Сушильная машина:"
        message: Сушка *закончена*, не забудьте достать белье.

- alias: Dishwasher - Dishwashing Finished Notification
  id: 9ef4d500-e688-4b70-b565-43ebb754bfe2
  triggers:
    - trigger: state
      entity_id: binary_sensor.dishwasher_status
      from: "on"
      to: "off"
  conditions: "{{ states('input_boolean.ha_shutdown') == 'off' }}"
  actions:
    - action: notify.telegram_group_flat_1
      data:
        title: "Посудомоечная машина:"
        message: Программа *закончена*, посуда вымыта.

- alias: Yandex Station SW Updated
  id: 3f22e8f0-6f31-49c1-bca1-ce19184c5184
  mode: queued
  max: 10
  triggers:
    - trigger: state
      entity_id:
        - sensor.yandex_station_lite_detskaia_sw_version
        - sensor.yandex_station_lite_prikhozhaya_sw_version
        - sensor.yandex_station_mini2_gostinaia_sw_version
        - sensor.yandex_station_mini2_spalnia_sw_version
  conditions:
    - "{{ trigger.to_state.state != trigger.from_state.state }}"
    - >
        {% set ignore = ['unknown', 'unavailable', 'none', None, null, '', 'null'] %}
        {{ trigger.to_state.state not in ignore and trigger.from_state.state not in ignore }}
  actions:
    - action: telegram_bot.send_message
      data:
        target: !secret tlg_group_system
        message: |
          _Yandex Station:_ Изменилась версия прошивки в
          {%- if 'detskaia' in trigger.entity_id %} *Детской*.
          {%- elif 'gostinaia' in trigger.entity_id %} *Гостиной*.
          {%- elif 'spalnia' in trigger.entity_id %} *Спальне*.
          {%- elif 'prikhozhaya' in trigger.entity_id %} *Прихожей*.
          {%- endif %}
          Было: {{ trigger.from_state.state }}
          Стало: {{ trigger.to_state.state }}
