#################################################
# Telegram Bot Automations
#################################################

# ---- Mirror all text messages
- alias: 'Telegram Bot - Mirror text'
  id: d35faec4-c949-4358-8aff-00e11b560444
  trigger:
    platform: event
    event_type: telegram_text
  action:
    service: notify.telegram_group_system
    data_template:
      message: |
        *{{ trigger.event.data.from_first }} {{ trigger.event.data.from_last }} [{{ trigger.event.data.user_id }}] пишет:*
        {{ trigger.event.data.text }}
# ---- /start
- alias: 'Telegram Bot - Start'
  id: d50c7e2c-9f67-40f2-9495-41ba1140c9b5
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/start'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/start@HAutoBot'
  action:
    service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: 'Привет! Помощь - /help'
# ---- /help
- alias: 'Telegram Bot - Help'
  id: 1e265eea-3d26-4a04-8402-f25a828f841d
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/help'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/help@HAutoBot'
  action:
    service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      parse_mode: html
      message: |
        Доступные комманды:
        /status - Текущий статус устройств
        /whoishome - Кто дома?
        /weather - Погода дома
        /weather_ch - Погода на даче
        /ping - Проверить доступность сервиса HASS
# ---- /ping
- alias: 'Telegram Bot - Ping'
  id: 936c648b-18b6-4636-a941-cc3f3361fdd0
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/ping'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/ping@HAutoBot'
  action:
    service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: |
        Pong! _{{ now().strftime("%d.%m.%Y %H:%M:%S") }}_
        Current version: {{ states('sensor.current_version') }}
        DB Size: {{ states('sensor.hass_db_size') }} {{ state_attr('sensor.hass_db_size','unit_of_measurement') }}
        Uptime: {{ states('sensor.ha_uptime') }} min.
# ---- /whoishome
- alias: 'Telegram Bot - Who is home?'
  id: f3af5ecc-3eb8-4542-8207-97f90b6f5abf
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/whoishome'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/whoishome@HAutoBot'
  action:
    service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      message: |
        Сейчас дома:
        {%- set entites = expand('group.family_persons') %}{% for prs in entites %}{% if prs.state == "home" %}
        {{ prs.attributes.friendly_name }}{% endif %}{% endfor %}
        {% if is_state("group.family_persons", "not_home") %}Никого нет{% endif %}
# ---- /weather
- alias: 'Telegram Bot - Weather'
  id: b0b0a539-14fb-440c-b57c-269460961819
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/weather'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/weather@HAutoBot'
  action:
    - service: telegram_bot.send_photo
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        file: '/config/www/weather_icons/{{ states("weather.moskva_danilovskii") }}.webp'
        caption: |
          Температура {{ state_attr('weather.moskva_danilovskii', 'temperature') }}°C
          Ощущается как {{ states('sensor.moskva_danilovskii_temperature_feels_like') }}°C
          Влажность {{ state_attr('weather.moskva_danilovskii', 'humidity') }}%
          Давление {{ state_attr('weather.moskva_danilovskii', 'pressure') }} hPa ({{ states('sensor.moskva_danilovskii_pressure_mmhg') }} mmHg)
          Облачность {{ states('sensor.moskva_danilovskii_cloud_coverage') }}%
# ---- /weather_ch
- alias: 'Telegram Bot - Weather Country House'
  id: c5ac3f4b-80b8-479f-96bf-45274aeba2ec
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/weather_ch'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/weather_ch@HAutoBot'
  action:
    - service: telegram_bot.send_photo
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        file: '/config/www/weather_icons/{{ states("weather.nivki_2") }}.webp'
        caption: |
          Температура {{ state_attr('weather.nivki_2', 'temperature') }}°C
          Ощущается как {{ states('sensor.nivki_2_temperature_feels_like') }}°C
          Влажность {{ state_attr('weather.nivki_2', 'humidity') }}%
          Давление {{ state_attr('weather.nivki_2', 'pressure') }} hPa ({{ states('sensor.nivki_2_pressure_mmhg') }} mmHg)
          Облачность {{ states('sensor.nivki_2_cloud_coverage') }}%
# ---- /status
- alias: 'Telegram Bot - Status'
  id: 51572bf5-4960-4034-b09a-17d202c07c18
  trigger:
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/status'
    - platform: event
      event_type: telegram_command
      event_data: 
        command: '/status@HAutoBot'
  action:
    service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: |
        *Климат*
        Гостинная: *{{ states('sensor.0x158d0003230618_temperature') }}°C*, {{ states('sensor.0x158d0003230618_humidity') }}%
        Детская: *{{ states('sensor.0x158d0003931aec_temperature') }}°C*, {{ states('sensor.0x158d0003931aec_humidity') }}%
        Спальня: *{{ states('sensor.0x158d0003931b0e_temperature') }}°C*, {{ states('sensor.0x158d0003931b0e_humidity') }}%
        Ванная: *{{ states('sensor.0x158d0003931a55_temperature') }}°C*, {{ states('sensor.0x158d0003931a55_humidity') }}%
        Туалет: *{{ states('sensor.a4c138414e9a_temperature') }}°C*, {{ states('sensor.a4c138414e9a_humidity') }}%
        Кладовая: *{{ states('sensor.0x158d00039e2ecb_temperature') }}°C*, {{ states('sensor.0x158d00039e2ecb_humidity') }}%

        *Статус устройств*
        `-= Датчики протечки =-`
        Нептун (кладовая, туалет, ванна, кухня): *{{ states('binary_sensor.neptun_water_leakage') }}*
        Aqara кладовая: *{{ states('binary_sensor.0x158d000400e77d_moisture') }}*
        Aqara под ванной (слева): *{{ states('binary_sensor.0x158d0004030d84_moisture') }}*
        `-= Кондиционеры =-`
        Детская: *{{ states('binary_sensor.0x158d00039cf974_contact') }}*
        Гостинная: *{{ states('binary_sensor.0x158d0003d54725_contact') }}*
        Спальня: *{{ states('binary_sensor.0x158d0004073b67_contact') }}*
        `-= Свет =-`
        Споты в прихожей: *{{ states('light.sonoff_1000f2f14a') }}*
        Лампа в спальне: *{{ states('light.spalnia_stol') }}*
        Люстра в детской: *{{ states('light.detskaia') }}*
        Подсветка окна в детской: *{{ states('light.detskaia_podsvetka_na_okne') }}*
        Споты в коридоре: *{{ states('light.sonoff_1000f2a500') }}*
        Споты на кухне: *{{ states('light.sonoff_1000b72483') }}*
        Подсветка кухни: *{{ states('light.kukhnia_lenta') }}*
        Люстра на кухне: *{{ states('light.kukhnia_liustra') }}*
        Свет в кладовой: *{{ states('light.sonoff_1000b6831b') }}*
        Лампа на столе в гостиной: *{{ states('light.0x86bd7fffe616b72_light') }}*
        Бра в гостиной: *{{ states('light.sonoff_1000ab3c28') }}*
        Подсветка онка в гостиной: *{{ states('light.gostinaia_podsvetka_na_okne') }}*
        `-= Розетки =-`
        Розетка TP-Link SmartPlug 01: *{{ states('switch.tplink_smartplug_01') }}*
        Розетка TP-Link SmartPlug 02: *{{ states('switch.tplink_smartplug_02') }}*
        Розетка Xiaomi ZigBee Plug 01: *{{ states('switch.0x158d00033b702e_switch') }}*
        Розетка Xiaomi ZigBee Plug 02: *{{ states('switch.0x158d000391fb00_switch') }}*
        Розетка Xiaomi WiFi Plug 01: *{{ states('switch.mi_smartplugwifi_01') }}*
        Розетка Xiaomi WiFi Plug 02: *{{ states('switch.mi_smartplugwifi_02') }}*
        `-= ТВ =-`
        Спальня: *{{ states('media_player.samsungtv_ue43ru7470') }}*
        Гостинная: *{{ states('media_player.samsungtv_ue46es5507') }}*
        Кухня: *{{ states('media_player.samsungtv_ue32es5500') }}*
        Детская: *{{ states('media_player.samsungtv_ue40c5100') }}*
        `-= Chromecast =-`
        Гостинная: *{{ states('media_player.gostinaia') }}*
        Гостинная (Home Mini): *{{ states('media_player.googlehome9967') }}*
        Детская: *{{ states('media_player.detskaia') }}*
        Детская: (Home Mini): *{{ states('media_player.googlehome3792') }}*
        `-= Разное =-`
        Входная дверь: *{{ states('sensor.entrance_door_status') }}*
        Mi Robot: *{{ states('vacuum.xiaomi_vacuum_cleaner') }}*
        Водонагреватель: *{{ states('sensor.boiler_status') }}* ({{ states('sensor.tplinksmartplug01_watts') }} W)
        Transmission Status: *{{ states('sensor.transmission_status') }}*
        Plex Users: *{{ states('sensor.plex_plexonubuntu') }}*