#################################################
# Lights Automations
#################################################

### Прихожая

- alias: "Кнопка Xiaomi в Прихожей single"
  id: 0783d105-f01b-488c-a4ee-14633d7b8d7e
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x158d00045a11b1_action
    to: "single"
  action:
    service: light.toggle
    data:
      entity_id: light.sonoff_1000f2f14a

- alias: "Кнопка Xiaomi в Прихожей double"
  id: 03118e47-0a7f-45a1-acbb-ad0d50a76927
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x158d00045a11b1_action
    to: "double"
  action:
    service: light.toggle
    data:
      entity_id: light.sonoff_1000f2a500

- alias: "Кнопка Xiaomi в Прихожей hold"
  id: 84c7e355-651c-4d59-9605-73590dc3423e
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x158d00045a11b1_action
    to: "hold"
  action:
    service: light.turn_off
    data:
      entity_id: group.all_lamps

- alias: "ДД Aqara включение света в прихожей"
  id: d3497859-d127-44ed-8980-be8963c0e618
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d000309920a_motion
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.sonoff_1000f2f14a
        state: "off"
      - condition: numeric_state
        entity_id: sensor.0x4cf8cdf3c7d110d_illuminance
        below: 30
  action:
    service: light.turn_on
    data:
      entity_id: light.sonoff_1000f2f14a

- alias: "ДД Aqara выключение света в прихожей"
  id: 3da7d0fb-89c4-4136-98cd-d52f0f3cede9
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d000309920a_motion
    to: "off"
  #    for:
  #      minutes: 3
  condition:
    condition: state
    entity_id: light.sonoff_1000f2f14a
    state: "on"
  action:
    service: light.turn_off
    entity_id: light.sonoff_1000f2f14a

- alias: "Вход в квартиру - включение света"
  id: bcadbe8a-b2cd-459c-924a-eb1d08876b3b
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.0x158d000309920a_motion
      state: "off"
  action:
    service: light.turn_on
    data:
      entity_id: light.sonoff_1000f2f14a

### Коридор

- alias: "Кнопка Xiaomi в Коридоре single"
  id: ea8dda71-4d1e-4e16-bd76-5d27bfffb975
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x158d00045a1153_action
    to: "single"
  action:
    service: light.toggle
    data:
      entity_id: light.sonoff_1000f2a500

- alias: "Кнопка Xiaomi в Коридоре double"
  id: aeb03ae7-3e12-41cf-ac87-7d291e7f7b9a
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x158d00045a1153_action
    to: "double"
  action:
    service: light.toggle
    data:
      entity_id: light.sonoff_1000f2f14a

- alias: "Кнопка Xiaomi в Коридоре hold"
  id: 35a01f66-3f67-4f9c-ae38-363f0581fe13
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x158d00045a1153_action
    to: "hold"
  action:
    service: light.turn_off
    data:
      entity_id:
        - group.light_detskaia
        - group.light_prikhozhaya
        - group.light_koridor
        - group.light_gostinaia
        - group.light_kukhnia
        - group.light_kladovaya

### Детская

- alias: "Kids must sleep at night"
  id: a2e4ec8e-926f-44bf-96fb-0029bd137f32
  initial_state: true
  trigger:
    platform: state
    entity_id: light.detskaia
    to: "on"
    for:
      minutes: 2
  condition:
    condition: time
    after: "00:00"
    before: "06:30"
  action:
    - service: homeassistant.turn_off
      entity_id: light.detskaia
    - service: notify.telegram_group_flat_1
      data:
        message: _{{ now().strftime("%d.%m.%Y %H:%M:%S") }}_ автоматически выключен свет в детской.

- alias: "Свет в детсокй Вкл-Выкл"
  id: dcd06f0b-d4da-4772-b2e7-c0c7a27f845d
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00033efd9e_action
      to: "single"
    - platform: state
      entity_id: sensor.0x158d00054859d5_action
      to: "single"
  action:
    - choose:
      - conditions: "{{ is_state('light.detskaia', 'unavailable') }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id: light.sonoff_zbmini_01_on_off
          - service: light.turn_on
            data:
              entity_id: light.sonoff_zbmini_01_on_off
          - wait_for_trigger:
            - platform: state
              entity_id: light.detskaia
              to: "on"
            timeout: "00:00:30"
          - service: light.turn_on
            target:
              entity_id: light.detskaia
            data:
              brightness: 255
      - conditions: "{{ is_state('light.sonoff_zbmini_01_on_off', 'off') }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.sonoff_zbmini_01_on_off
          - wait_for_trigger:
            - platform: state
              entity_id: light.detskaia
              to: "on"
            timeout: "00:00:30"
          - service: light.turn_on
            target:
              entity_id: light.detskaia
            data:
              brightness: 255
      - conditions: "{{ is_state('light.sonoff_zbmini_01_on_off', 'on') }}"
        sequence:
          - service: light.toggle
            data:
              entity_id: light.detskaia

- alias: "Подсветка окна в детской Вкл-Выкл"
  id: 6d473a7d-6cfd-4dd7-a3a4-061a1e73e23d
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00033efd9e_action
      to: "hold"
    - platform: state
      entity_id: sensor.0x158d00054859d5_action
      to: "double"
  action:
    service: switch.toggle
    data:
      entity_id: switch.0x158d00033b702e_switch

- alias: "Яркость света в детской"
  id: d4ce60e4-9bd5-446d-ac4d-035d903e5066
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00033efd9e_action
      to: "double"
    - platform: state
      entity_id: sensor.0x158d00033efd9e_action
      to: "triple"
  action:
    - choose:
      - conditions: "{{ trigger.to_state.state == 'double' }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: light.detskaia
              transition: "0.5"
              brightness: >
                {%- if (state_attr('light.detskaia', 'brightness') | int) <= 3 %}
                  51
                {% elif (state_attr('light.detskaia', 'brightness') | int) <= 51 %}
                  102
                {% elif (state_attr('light.detskaia', 'brightness') | int) <= 102 %}
                  153
                {% elif (state_attr('light.detskaia', 'brightness') | int) <= 153 %}
                  204
                {% elif (state_attr('light.detskaia', 'brightness') | int) <= 204 %}
                  255
                {% elif (state_attr('light.detskaia', 'brightness') | int) <= 255 %}
                  3
                {% endif %}
      - conditions: "{{ trigger.to_state.state == 'triple' }}"
        sequence:
          - service: light.turn_on
            data_template:
              entity_id: light.detskaia
              transition: "0.5"
              brightness: 255

- alias: Sunrise Lighting (Nursery)
  id: d50bfe78-2e35-4870-a24c-71d0f6ebf969
  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.sunrise_in_nursery
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: sun
        before: sunrise
        before_offset: "00:30:00"
  action:
    - service: light.turn_on
      entity_id: light.detskaia
      data:
        effect: Sunrise

### Кухня

- alias: "Подсветка на кухне (кнопка Xiaomi)"
  id: e5c30f0b-e56d-4b03-b81f-f40998909831
  trigger:
    platform: state
    entity_id: sensor.0x158d00035ff631_action
    to: "single"
  action:
    service: light.toggle
    data:
      entity_id: light.kukhnia_lenta

- alias: "Люстра на кухне (кнопка Xiaomi)"
  id: 050e258b-ff2c-4da2-8676-030e0eda668d
  trigger:
    platform: state
    entity_id: sensor.0x158d00035ff631_action
    to: "double"
  action:
    service: light.toggle
    data:
      entity_id: light.kukhnia_liustra

- alias: "Подсветка на кухне (сенсор движения - вкл)"
  id: 72c4f7ac-f72c-47fd-bf06-6e3671d12b1d
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003fac0ec_motion
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "21:00"
        before: "09:00"
      - condition: numeric_state
        entity_id: sensor.0x158d0003fac0ec_illuminance
        below: 15
  action:
    service: homeassistant.turn_on
    entity_id: light.kukhnia_lenta

- alias: "Подсветка на кухне (сенсор движения - выкл)"
  id: 47413029-b8c2-4ec1-ad98-7c72b271766d
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003fac0ec_motion
    to: "off"
    for:
      minutes: 3
  condition:
    condition: time
    after: "21:00"
    before: "09:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.kukhnia_lenta

### Кладовая

- alias: "Свет в кладовой (сенсор движения - вкл)"
  id: 58129c01-7211-47c8-83f4-a954a88bea9f
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003045123_motion
    to: "on"
  condition:
    condition: state
    entity_id: light.sonoff_1000b6831b
    state: "off"
  action:
    service: light.turn_on
    entity_id: light.sonoff_1000b6831b

- alias: "Свет в Кладовой (сенсор движения - выкл)"
  id: b1d55360-e2e7-41a9-8552-8367bf84d712
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003045123_motion
    to: "off"
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: light.sonoff_1000b6831b
    state: "on"
  action:
    service: light.turn_off
    entity_id: light.sonoff_1000b6831b

# Спальня

- alias: "Кнопки Xiaomi в Спальне single"
  id: 28d3fc25-b07c-4a8e-8da9-ca60d730da41
  trigger:
    - platform: state
      entity_id: sensor.0x158d0003d17762_action
      to: "single"
    - platform: state
      entity_id: sensor.0x158d0003d15d00_action
      to: "single"
  action:
    - service: light.toggle
      data:
        entity_id: light.sonoff_1001053235

- alias: "Кнопки Xiaomi в Спальне double"
  id: a7d07612-155d-481b-9357-9bfdcaba8057
  trigger:
    - platform: state
      entity_id: sensor.0x158d0003d17762_action
      to: "double"
    - platform: state
      entity_id: sensor.0x158d0003d15d00_action
      to: "double"
  action:
    choose:
      - alias: If Group is On
        conditions:
          - condition: state
            entity_id: group.light_spalnia_bra
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            data:
              entity_id: group.light_spalnia_bra
      - alias: If Group is Off
        conditions:
          - condition: state
            entity_id: group.light_spalnia_bra
            state: "off"
        sequence:
          - service: homeassistant.turn_on
            data:
              entity_id: group.light_spalnia_bra

- alias: "Кнопки Xiaomi в Спальне hold"
  id: 7a0d0886-9eaf-4286-a70f-e1dd049484e7
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d0003d17762_action
      to: "hold"
    - platform: state
      entity_id: sensor.0x158d0003d15d00_action
      to: "hold"
  action:
    service: light.turn_off
    data:
      entity_id: group.all_lamps


- alias: "Кнопки IKEA в Спальне"
  id: ffd8dce9-55d7-449c-a5ed-280604c00930
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "84:fd:27:ff:fe:90:a6:46"
      id: "ikea_sw_1"
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "84:fd:27:ff:fe:9e:e4:06"
      id: "ikea_sw_2"
  action:
    choose:
      - alias: 'command: on'
        conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: light.toggle
            data:
              entity_id: light.sonoff_1001053235
      - alias: "command: off"
        conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          choose:
            - alias: 'If Group is On'
              conditions:
                - condition: state
                  entity_id: group.light_spalnia_bra
                  state: "on"
              sequence:
                - service: homeassistant.turn_off
                  data:
                    entity_id: group.light_spalnia_bra
            - alias: 'If Group is Off'
              conditions:
                - condition: state
                  entity_id: group.light_spalnia_bra
                  state: "off"
              sequence:
                - service: homeassistant.turn_on
                  data:
                    entity_id: group.light_spalnia_bra
      - alias: 'command: move_with_on_off'
        conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - service: light.toggle
            data:
              entity_id: light.spalnia_stol
      - alias: 'command: move'
        conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id: group.all_lamps


- alias: Sunrise Lighting (Bedroom)
  id: 35fa00c7-72bd-4a5f-9bef-7bcf13a3bf49
  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.sunrise_in_bedroom
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: sun
        before: sunrise
        before_offset: "00:30:00"
  #    - condition: state
  #      entity_id: sun.sun
  #      state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.spalnia_stol
      data:
        effect: SunriseBW

# Гостиная

# Споты
- alias: "Кнопка Xiaomi в Гостиной single"
  id: 90058a3d-e36b-4384-a304-bf7ce2f4752d
  trigger:
    platform: state
    entity_id: sensor.0x158d00035a9bc5_action
    to: "single"
  action:
    - service: light.toggle
      data:
        entity_id: light.sonoff_1000ab3c28
  # Люстра
- alias: "Кнопка Xiaomi Гостиная double"
  id: 228250e9-ff19-419b-9817-2fb812f0be76
  trigger:
    platform: state
    entity_id: sensor.0x158d00035a9bc5_action
    to: "double"
  action:
    - service: light.toggle
      data:
        entity_id: light.sonoff_1000f3035d

- alias: "Кнопка Aqara 1 single"
  id: 07c60bca-a9a9-4ad1-9bc5-7e3776d55f31
  trigger:
    platform: state
    entity_id: sensor.0x158d0004ab468e_action
    to: "single"
  action:
    - service: light.toggle
      data:
        entity_id: light.0x86bd7fffe616b72_light

- alias: "Кнопка Aqara 1 double"
  id: d7cb6c13-4f80-46cd-9c3b-a862657f1db0
  trigger:
    platform: state
    entity_id: sensor.0x158d0004ab468e_action
    to: "double"
  action:
    - service: light.toggle
      data:
        entity_id: light.sonoff_1000b72483

- alias: "Кнопка Aqara 1 hold"
  id: 07cd182d-1013-4e32-94f7-b6f20a232c73
  trigger:
    platform: state
    entity_id: sensor.0x158d0004ab468e_action
    to: "hold"
  action:
    - service: light.toggle
      data:
        #          entity_id: light.kukhnia_liustra
        entity_id: light.sonoff_1000ab3c28

- alias: "Кнопка Aqara 1 shake"
  id: 4d769d02-55d5-41aa-a59c-68c08154eeff
  trigger:
    platform: state
    entity_id: sensor.0x158d0004ab468e_action
    to: "shake"
  action:
    - service: light.toggle
      data:
        entity_id: light.gostinaia_podsvetka_na_okne

# Разное

- alias: Aqara Cube Rotate
  id: bca58eda-70ce-431c-893f-8ba0baeb7c56
  mode: queued
  max: 5
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:15:8d:00:05:29:2a:d9"
        command: "rotate_left"
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:15:8d:00:05:29:2a:d9"
        command: "rotate_right"
  action:
    - service: light.turn_on
      entity_id: light.0x86bd7fffe616b72_light
      data:
        brightness: >-
          {{ (state_attr('light.0x86bd7fffe616b72_light', 'brightness') | int) +
          (trigger.event.data.args.relative_degrees | int) }}

- alias: Aqara Cube Flip 90
  id: ebb64a34-ef85-4cf8-a450-d57a9dcb51b6
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:15:8d:00:05:29:2a:d9"
        command: "flip"
  condition:
    - condition: template
      value_template: >-
        {{ (trigger.event.data.args.flip_degrees | int) == 90 }}
  action:
    - service: light.toggle
      entity_id: light.0x86bd7fffe616b72_light
      data:
        brightness: 255

- alias: Aqara Cube Flip 180
  id: c5563c01-dca4-4e46-940f-1ee5cd15e4c9
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:15:8d:00:05:29:2a:d9"
        command: "flip"
  condition:
    - condition: template
      value_template: >-
        {{ (trigger.event.data.args.flip_degrees | int) == 180 }}
  action:
    - service: light.toggle
      entity_id: light.sonoff_1000f30a9e