#################################################
# System
#################################################

#- alias: "Restart FFmpeg process"
#  initial_state: false
#  trigger:
#    platform: state
#    entity_id: binary_sensor.dvizhenie_v_detskoi
#    to: 'unavailable'
#  action:
#    - service: ffmpeg.restart
#    - service: notify.telegram_stall
#      data:
#        message: "_INFO:_ Перезапущен процесс ffmpeg"
#    - delay:
#        seconds: 10

#- alias: "Temporary - Dismiss Discovery Notifications"
#  initial_state: true
#  trigger:
#    - platform: event
#      event_type: config_entry_discovered
#  action:
#    - service: persistent_notification.dismiss
#      data:
#        notification_id: config_entry_discovery

- alias: "HASSIO: Create Snapshot [notify to stall]"
  initial_state: true
  trigger:
    - platform: time
      at: "02:45:00"
  condition:
    - condition: time
      weekday:
        - thu
  action:
    - service: auto_backup.snapshot_full
      data_template:
        name: >
          hassio_weekly_backup_{{ now().strftime('%Y%m%d') }}
        keep_days: 13
    - service: notify.telegram_stall
      data:
        message: _INFO:_ Создан еженедельный бэкап HASSIO

- alias: "HASS: ERRORs in System Log - Counter"
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
  mode: parallel
  max: 25
  action:
    - service: counter.increment
      entity_id: counter.syslog_errors

- alias: "HASS: WARNINGs in System Log - Counter"
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
  mode: parallel
  max: 25
  action:
    - service: counter.increment
      entity_id: counter.syslog_warnings

- alias: "HASS: Create Group of Battery Devices"
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/2"
  action:
    - service: group.set
      data_template:
        object_id: battery_devices
        entities: >-
          {%- 
            for state in states.sensor 
              if is_state_attr(state.entity_id, 'device_class', 'battery') and
              (state.entity_id.endswith("_battery") or state.entity_id.endswith("_power"))
          %}
          {{ state.entity_id }}{%- if not loop.last -%}, {%- endif -%}
          {%- endfor %}

#- alias: "Mirror Notifications from Android's to Telegram"
#  trigger:
#    - platform: state
#      entity_id:
#        - sensor.kb2003_poslednee_uvedomlenie
#        - sensor.mi_8_poslednee_uvedomlenie
#  action:
#    - service: notify.telegram_stall
#      data:
#        message: |
#          {{ trigger.to_state.attributes.package }}
#          {{ trigger.to_state.state }}