#################################################
# Media automatization
#################################################

- alias: "PowerOff all media when nobody at home"
  id: 0e2312c7-3cab-413a-aefb-20ff5802c718
  triggers:
    trigger: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  conditions:
    - or:
      - condition: state
        entity_id: group.all_tv
        state: "on"
      - condition: state
        entity_id: group.all_chromecasts
        state: "on"
      - condition: state
        entity_id:
          - media_player.yandex_station_lite_detskaia
          - media_player.yandex_station_mini2_gostinaia
          - media_player.yandex_station_mini2_spalnia
          - media_player.yandex_station_lite_prikhozhaya
        state: "playing"
      - condition: state
        entity_id: group.all_xbox
        state: "on"
  actions:
    - action: homeassistant.turn_off
      target:
        entity_id: group.all_tv
    - action: media_player.media_stop
      target:
        entity_id:
          - group.all_chromecasts
    - action: media_player.turn_off
      target:
        entity_id:
          - group.all_yandex_stations
          - group.all_xbox
