#################################################
# CCTV
#################################################

- alias: Движение в детской
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00044cea8e
    from: 'off'
    to: 'on'
  action:
    - service: notify.telegram_stall
      data:
        message: "В *Детской* обнаружено движение:"
    - service: notify.telegram_stall
      data_template:
        message: "Camera Snapshot 1"
        data:
          photo:
#            - url: !secret cloudcam01_url
            - url: !secret dafangcam_03_snapshot_url
    - delay:
        seconds: 1
    - service: notify.telegram_stall
      data:
        message: "Camera Snapshot 2"
        data:
          photo:
            - url: !secret dafangcam_03_snapshot_url
    - delay:
        seconds: 1
    - service: notify.telegram_stall
      data:
        message: "Camera Snapshot 3"
        data:
          photo:
            - url: !secret dafangcam_03_snapshot_url

- alias: 'Вкл контроль движения в детской'
  initial_state: true
  trigger:
    platform: time
    at: "23:30:00"
  action:
    - service: automation.turn_on
      entity_id: automation.dvizhenie_v_detskoi

- alias: 'Выкл контроль движения в детской'
  initial_state: true
  trigger:
    platform: time
    at: "07:00:00"
  action:
    - service: automation.turn_off
      entity_id: automation.dvizhenie_v_detskoi

- alias: Вход в квартиру
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00031c790f
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d000309920a
      state: 'off'
  action:
    - delay:
        seconds: 2
    - service: notify.telegram_stall
      data_template:
        message: "Camera Snapshot 1"
        data:
          photo:
            - url: !secret dafangcam_02_snapshot_url
    - delay:
        seconds: 1
    - service: notify.telegram_stall
      data_template:
        message: "Camera Snapshot 2"
        data:
          photo:
            - url: !secret dafangcam_02_snapshot_url
    - delay:
        seconds: 2
    - service: notify.telegram_stall
      data_template:
        message: "Camera Snapshot 3"
        data:
          photo:
            - url: !secret dafangcam_02_snapshot_url
    - delay:
        seconds: 3
    - service: notify.telegram_stall
      data_template:
        message: "Camera Snapshot 4"
        data:
          photo:
            - url: !secret dafangcam_02_snapshot_url