#################################################
# Notifications
#################################################

- alias: 'Home Presence Alert'
  initial_state: true
  trigger:
    platform: state
    entity_id: person.alexander, person.irina, person.galina, person.tatiana, person.olga
  condition:
    condition: and
    conditions:
#      - condition: template
#        value_template: "{{ states('sensor.uptime') != '0.0' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: notify.telegram_stall
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }}
          {% if trigger.to_state.state == 'home' %}дома!
          {% else %}скорее всего вне дома.
          {% endif %}

- alias: 'HASS: Home Assistant Start'
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: notify.telegram_stall
    data:
      message: "_INFO:_ Home Assistant *запущен*."

- alias: 'HASS: Home Assistant Shutdown'
  initial_state: true
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.telegram_stall
      data:
        message: "_INFO:_ Home Assistant *остановлен*."

- alias: 'HASS: ERRORs in System Log [notify to stall]'
  initial_state: false
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
  action:
    - service: notify.telegram_stall
      data_template:
        message: "_{{ trigger.event.data.level }}:_ {{ trigger.event.data.message }}"

- alias: 'HASS: WARNINGs in System Log [notify to stall]'
  initial_state: false
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
  action:
    - service: notify.telegram_stall
      data_template:
        message: "_{{ trigger.event.data.level }}:_ {{ trigger.event.data.message }}"

- alias: 'HASSIO: New Version Available [notify to stall]'
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ states('sensor.current_version') < states('sensor.latest_version') }}"
  action:
    service: notify.telegram_stall
    data_template:
      message: "_INFO:_ Доступна новая версия Home Assistant ({{ states('sensor.latest_version') }})"

- alias: 'HASSIO: New Addons Update Available [notify to stall]'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.updater_addons
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ states('sensor.supervisor_updates') | int > 0 }}"
  action:
    - service: notify.telegram_stall
      data_template:
        message: "_INFO:_ Доступны новые версии Add-ons (Supervisor) (кол-во: {{ states('sensor.supervisor_updates') }})"

- alias: 'HASSIO: New Supervisor Version Available [notify to stall]'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.updater_supervisor
      from: 'off'
      to: 'on'
  action:
    - service: notify.telegram_stall
      data_template:
        message: "_INFO:_ Доступна новая версия Supervisor ({{ state_attr('sensor.supervisor_updates', 'newest_version') }})"

- alias: 'HACS: New Component Version Available [notify to stall]'
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.hacs
  condition:
    - condition: template
      value_template: "{{ (states('sensor.hacs') | int) > 0 }}"
  action:
    service: notify.telegram_stall
    data_template:
      message: "_INFO:_ Доступны новые версии Custom Components (HACS) (кол-во: {{ states('sensor.hacs') }})"

- alias: Torrent Completed [notify to stall]
  initial_state: true
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.telegram_stall
    data_template:
      message: "Загрузка torrent-файла завершена"

- alias: Полнолуние [notify to stall]
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.moon
    to: "full_moon"
  action:
    service: notify.telegram_stall
    data_template:
      message: "Сегодня полнолуние!"

- alias: 'Low Battery Alert'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.0x158d0003230618_battery
      - sensor.0x158d0003931aec_battery
      - sensor.0x158d0003931b0e_battery
      - sensor.0x158d00035ff631_battery
      - sensor.0x158d0003045123_battery
      - sensor.0x158d0003931a55_battery
      - sensor.0x158d00039e2ecb_battery
      - sensor.0x158d000400e77d_battery
      - sensor.0x158d000309920a_battery
      - sensor.0x158d00044cea8e_battery
      - sensor.0x158d00031c790f_battery
      - sensor.0x158d00039cf974_battery
      - sensor.0x158d0004073b67_battery
      - sensor.0x158d0003d54725_battery
      - sensor.0x158d00033efd9e_battery
      - sensor.0x158d00035a9bc5_battery
      - sensor.a4c138414e9a_battery
      - sensor.0x158d00044ee524_battery
      - sensor.0x158d0004ab468e_battery
      - sensor.0x158d0004030d84_battery
      - sensor.0x158d00054859d5_battery
      - sensor.e72e0081ac21_battery
      - sensor.a4c1387179f4_battery
      - sensor.a4c1381b3d13_battery
      - sensor.a4c13820bdae_battery
    below: 15
  action:
    - service: notify.telegram_stall
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} {{ trigger.to_state.state }}%!

- alias: Entrance Door - Opened
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: 'off'
    to: 'on'
  action:
    service: notify.telegram_stall
    data:
      message: Открыта входная дверь!

- alias: Entrance Door - Closed
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: 'on'
    to: 'off'
  action:
    service: notify.telegram_stall
    data:
      message: Входная дверь закрыта.

- alias: Gas Alert
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d000413b210_gas
    from: 'off'
    to: 'on'
  action:
    service: notify.telegram_stall
    data:
      title: "*Внимание!*"
      message: |
        Сработал датчик *газа* на кухне.
        Откройте окна и перекройте подачу газа (за холодильником).

- alias: New Network Device Notification
  initial_state: true
  mode: parallel
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: notify.telegram_stall
    data_template:
      title: "*Найдено новое устройство в сети!*"
      message: |
        MAC: {{ trigger.event.data.mac }}
