push_indications:
  description: 'Передать показания в личный кабинет'
  target:
    entity:
      integration: lkcomu_interrao
      domain: sensor
  fields:
    indications:
      description: 'Список показаний (от 1 до 3) для тарифов: T1, T2, T3'
      required: true
      advanced: false
      example: '123, 456, 789'
      selector:
        text:
          multiline: false
    incremental:
      description: 'Сложить известные переданные показания счётчика с передаваемыми'
      required: false
      advanced: false
      default: false
      example: 'false'
      selector:
        boolean:
    ignore_period:
      description: 'Игнорировать ограничения по периоду'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:
    ignore_indications:
      description: 'Игнорировать ограничения по показаниям'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:

calculate_indications:
  description: 'Подсчитать начисления по передаваемым показаниям'
  target:
    entity:
      integration: lkcomu_interrao
      domain: sensor
  fields:
    indications:
      description: 'Список показаний (от 1 до 3) для тарифов: T1, T2, T3'
      required: true
      advanced: false
      example: '123, 456, 789'
      selector:
        text:
          multiline: false
    incremental:
      description: 'Сложить известные переданные показания счётчика с передаваемыми'
      required: false
      advanced: false
      default: false
      example: 'false'
      selector:
        boolean:
    ignore_period:
      description: 'Игнорировать ограничения по периоду'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:
    ignore_indications:
      description: 'Игнорировать ограничения по показаниям'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:


set_description:
  description: "Задать комментарий к лицевому счёту. Пустой параметр `description` (или его упущение) очистит описание к лицевому счёту."
  target:
    entity:
      integration: lkcomu_interrao
      domain: sensor
  fields:
    description:
      description: 'Описание'
      required: false
      advanced: false
      selector:
        text:
          multiline: false

get_payments:
  description: "Получить перечень платежей, связанных с лицевым счётом, которые находятся внутри заданного периода"
  target:
    entity:
      integration: lkcomu_interrao
      domain: sensor
  fields:
    start:
      description: "Дата начала периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false
    end:
      description: "Дата окончания периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false

get_invoices:
  description: "Получить перечень квитанций, связанных с лицевым счётом, которые находятся внутри заданного периода"
  target:
    entity:
      integration: lkcomu_interrao
      domain: sensor
  fields:
    start:
      description: "Дата начала периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false
    end:
      description: "Дата окончания периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false