request_api:
  fields:
    device_id:
      selector:
        device:
          integration: ha_keenetic
          manufacturer: Keenetic Ltd.
    entry_id:
      selector:
        config_entry:
          integration: ha_keenetic
    method:
      required: true
      selector:
        select:
          options:
            - GET
            - POST
    endpoint:
      required: true
      example: "/rci/show/version"
      selector:
        template:
    data_json:
      required: false
      selector:
        template:
backup_router:
  fields:
    device_id:
      selector:
        device:
          integration: ha_keenetic
          manufacturer: Keenetic Ltd.
    entry_id:
      selector:
        config_entry:
          integration: ha_keenetic
    folder:
      required: true
      selector:
        template:
    type:
      required: true
      example:
        - firmware
        - config
      selector:
        select:
          multiple: true
          options:
            - firmware
            - config
