substitutions:
  esp_board: esp32dev
  board_name: esp32-bt-proxy-02
  room_name: Hallway

#external_components: 
#  - source: github://myhomeiot/esphome-components

packages:
  wifi: !include common/wifi_bt_proxy.yaml
  device_base: !include common/device_base_esp32_bt_proxy.yaml
  esp32_ble_tracker: !include common/esp32_ble_tracker_bt_proxy.yaml
  family_ibeacon_sensors: !include common/family_ibeacon_sensors.yaml

status_led:
  pin: GPIO2

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  on_ble_service_data_advertise:
    - mac_address: F9:9D:1D:40:23:40
      service_uuid: "5242"
      then:
#        - lambda: 'id(black1_battery).publish_state(x[1]);' # catch battary %
        - lambda: |-
            if (x[11] == 1.0) {
              id(black1_button).publish_state(true);
            } else {
              id(black1_button).publish_state(false);
            }
            id(black1_battery).publish_state(x[1]);

    - mac_address: E6:9F:37:5B:1D:DA
      service_uuid: "5242"
      then:
        - lambda: 'id(white1_battery).publish_state(x[1]);'

sensor:
  - platform: template
    name: "Holy-IoT Black-1 Battery"
    id: black1_battery
    device_class: "battery"
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    accuracy_decimals: 0

  - platform: template
    name: "Holy-IoT White-1 Battery"
    id: white1_battery
    device_class: "battery"
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    accuracy_decimals: 0


binary_sensor:
  - platform: template
    name: "Holy-IoT Black-1 Button"
    id: black1_button