substitutions:
  board_name: sonoff_mini_r2_04
  esp_board: esp8285
  room_name: Country House

packages:
  wifi: !include common/wifi_ch.yaml
  device_base: !include common/device_base_8266.yaml

esphome:
  on_boot:
    then:
      - switch.turn_off: relay

web_server:
  port: 80

#######################################
# Device specific Config Begins Below #
#######################################

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay

  - platform: gpio
    pin: GPIO04
    id: button_sw
    internal: true
    on_press:
      then:
        - switch.toggle:
            id: relay
    on_release:
      then:
        - switch.toggle:
            id: relay

switch:
  - platform: gpio
    internal: true
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "${board_name} Switch"
    icon: mdi:power
    optimistic: true
    id: button_switch
    turn_on_action:
      - switch.turn_on: relay
    turn_off_action:
      - switch.turn_off: relay

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  - platform: monochromatic
    name: ${board_name}_blueled
    output: blue_led
    internal: true
    restore_mode: ALWAYS_OFF