substitutions:
  board_name: sonoff_basic_04
  esp_board: esp01_1m
  room_name: Country House

packages:
  wifi: !include common/wifi_ch.yaml
  device_base: !include common/device_base_8266.yaml

esp8266:
  restore_from_flash: True

#esphome:
#  on_boot:
#    - switch.turn_off: button_sw

wifi:
  use_address: 192.168.10.117

web_server:
  port: 80

binary_sensor:
  # Button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${board_name} Button state"
    on_press:
      - switch.toggle: button_sw

switch:
  # Relay switch
  - platform: gpio
    id: relay
    pin: GPIO12
    #restore_mode: ALWAYS_OFF
    restore_mode: RESTORE_DEFAULT_OFF

  # Template switch for button
  - platform: template
    name: "${board_name} Switch"
    optimistic: true
    id: button_sw
    turn_on_action:
    - switch.turn_on: relay
#    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
#    - light.turn_off: led

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "${board_name} Led"
    output: basic_green_led
    id: led