send_command:
  name: Send command
  description: Send command to Gateway
  fields:
    host:
      name: Host
      description: Gateway IP address
      example: 192.168.1.123
      selector:
        text:
    command:
      name: Command
      description: pair, bind, ota, config, parentscan, firmwarelock, reboot, ftp, flashzb, openmiio_reload
      selector:
        text:
    data:
      name: Data
      description: Depends on command...
      selector:
        text:
